# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-25 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='urlt',
            field=models.URLField(null=True),
        ),
    ]
